const path = require('path');
const fs = require('fs');
const { marked } = require('marked');
const docx = require('docx');
const { saveGeneratedFile } = require('../manager');
const { getTheme, getMargins, htmlToDocxElements } = require('./utils');

async function createDocx(params) {
  const {
    filename = 'document.docx',
    title = '',
    subtitle = '',
    author = '',
    content = '',
    theme = 'neutral',
    margins = 'normal',
    includeTitlePage = false,
    outputDir,
  } = params;

  if (!outputDir) {
    throw new Error('outputDir is required');
  }

  const displayFilename = filename.endsWith('.docx') ? filename : `${filename}.docx`;
  const documentTitle = title || content.match(/^#\s+(.+)$/m)?.[1] || displayFilename.replace(/\.docx$/i, '');

  const themeColors = getTheme(theme);
  const marginConfig = getMargins(margins);

  const { Document, Packer, Paragraph, TextRun } = docx;

  marked.setOptions({ gfm: true, breaks: true });
  const html = marked.parse(content);

  let docElements = htmlToDocxElements(html, docx, themeColors);

  if (docElements.length === 0) {
    docElements = [new Paragraph({ children: [new TextRun({ text: content })] })];
  }

  const sections = [];

  if (includeTitlePage) {
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    sections.push({
      properties: {
        page: { margin: marginConfig },
      },
      children: [
        new Paragraph({ spacing: { before: 2000 }, children: [] }),
        new Paragraph({
          alignment: 'center',
          children: [new TextRun({ text: documentTitle, bold: true, size: 48, color: themeColors.heading })],
        }),
        new Paragraph({ spacing: { before: 400 }, children: [] }),
        ...(subtitle ? [new Paragraph({
          alignment: 'center',
          children: [new TextRun({ text: subtitle, size: 28, color: themeColors.accent })],
        })] : []),
        new Paragraph({ spacing: { before: 800 }, children: [] }),
        ...(author ? [new Paragraph({
          alignment: 'center',
          children: [new TextRun({ text: `By ${author}`, size: 24 })],
        })] : []),
        new Paragraph({ spacing: { before: 400 }, children: [] }),
        new Paragraph({
          alignment: 'center',
          children: [new TextRun({ text: currentDate, size: 24 })],
        }),
      ],
    });

    sections.push({
      properties: {
        page: { margin: marginConfig },
      },
      children: docElements,
    });
  } else {
    sections.push({
      properties: {
        page: { margin: marginConfig },
      },
      children: docElements,
    });
  }

  const doc = new Document({
    title: documentTitle,
    creator: 'Hermind',
    description: 'Word Document generated by Hermind',
    sections,
  });

  const buffer = await Packer.toBuffer(doc);

  const saved = saveGeneratedFile(outputDir, 'docx', 'docx', buffer, displayFilename);
  return saved.storagePath;
}

module.exports = { createDocx };
