package cli

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// newSetupCmd creates the "hermind setup" wizard.
func newSetupCmd(app *App) *cobra.Command {
	return &cobra.Command{
		Use:   "setup",
		Short: "Scriptable configuration writer (prefer `hermind config` for interactive use)",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runSetupInteractive(bufio.NewReader(os.Stdin))
		},
	}
}

// runSetupInteractive walks the user through minimum config and
// writes ~/.hermind/config.yaml. The file is rendered from a template
// that includes commented-out blocks for every supported provider so
// users can enable additional ones by uncommenting.
func runSetupInteractive(reader *bufio.Reader) error {
	fmt.Println("hermind setup — interactive configuration wizard")
	fmt.Println("This writes ~/.hermind/config.yaml. Press Enter to accept defaults.")
	fmt.Println("Tip: `hermind config` is the interactive TUI editor for an existing config.")
	fmt.Println()

	provider := prompt(reader, "Primary provider [anthropic]", "anthropic")
	apiKey := prompt(reader, fmt.Sprintf("%s api key (leave blank to use env var)", provider), "")
	model := prompt(reader, "Default model [claude-opus-4-6]", "claude-opus-4-6")
	terminalBackend := prompt(reader, "Terminal backend [local]", "local")
	storagePath := prompt(reader, "SQLite path [~/.hermind/state.db]", "~/.hermind/state.db")

	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	cfgDir := filepath.Join(home, ".hermind")
	if err := os.MkdirAll(cfgDir, 0o755); err != nil {
		return err
	}
	cfgPath := filepath.Join(cfgDir, "config.yaml")

	content := renderConfigTemplate(provider, apiKey, model, terminalBackend, storagePath)
	if err := os.WriteFile(cfgPath, []byte(content), 0o644); err != nil {
		return err
	}
	fmt.Printf("\nwrote %s\n", cfgPath)
	fmt.Println("run `hermind doctor` to verify your setup.")
	return nil
}

// providerTemplate describes a single provider block for the default
// config. EnvVar is the conventional environment variable name suggested
// in the comment.
type providerTemplate struct {
	Name    string
	BaseURL string
	Model   string
	EnvVar  string
}

// allProviders enumerates every provider supported by the factory.
// Order is significant: it determines the order in the generated file.
var allProviders = []providerTemplate{
	{"anthropic", "https://api.anthropic.com", "claude-opus-4-6", "ANTHROPIC_API_KEY"},
	{"openai", "https://api.openai.com/v1", "gpt-4o", "OPENAI_API_KEY"},
	{"openrouter", "https://openrouter.ai/api/v1", "anthropic/claude-3.5-sonnet", "OPENROUTER_API_KEY"},
	{"deepseek", "https://api.deepseek.com/v1", "deepseek-chat", "DEEPSEEK_API_KEY"},
	{"qwen", "https://dashscope.aliyuncs.com/compatible-mode/v1", "qwen-max", "DASHSCOPE_API_KEY"},
	{"zhipu", "https://open.bigmodel.cn/api/paas/v4", "glm-4-plus", "ZHIPU_API_KEY"},
	{"kimi", "https://api.moonshot.cn/v1", "moonshot-v1-32k", "MOONSHOT_API_KEY"},
	{"minimax", "https://api.minimax.chat/v1", "abab6.5-chat", "MINIMAX_API_KEY"},
	{"wenxin", "", "ernie-4.0-8k", "WENXIN_API_KEY"},
}

func renderConfigTemplate(activeProvider, apiKey, model, terminalBackend, storagePath string) string {
	var b strings.Builder
	b.WriteString("# hermind configuration — generated by `hermind setup`.\n")
	b.WriteString("# Uncomment additional provider blocks below to enable them.\n")
	b.WriteString("# Paste API keys as literal strings, e.g. api_key: \"sk-ant-...\"\n\n")

	fmt.Fprintf(&b, "model: %s/%s\n\n", activeProvider, model)

	b.WriteString("providers:\n")
	wroteActive := false
	for _, p := range allProviders {
		if p.Name == activeProvider {
			b.WriteString(activeProviderBlock(p, apiKey, model))
			b.WriteString("\n")
			wroteActive = true
		}
	}
	if !wroteActive {
		b.WriteString(activeProviderBlock(providerTemplate{
			Name:   activeProvider,
			Model:  model,
			EnvVar: strings.ToUpper(activeProvider) + "_API_KEY",
		}, apiKey, model))
		b.WriteString("\n")
	}

	b.WriteString("  # --- Uncomment any of the providers below to enable them ---\n\n")
	for _, p := range allProviders {
		if p.Name == activeProvider {
			continue
		}
		b.WriteString(commentedProviderBlock(p))
		b.WriteString("\n")
	}

	b.WriteString("agent:\n")
	b.WriteString("  max_turns: 90\n")
	b.WriteString("  gateway_timeout: 1800\n")
	b.WriteString("  compression:\n")
	b.WriteString("    enabled: true\n")
	b.WriteString("    threshold: 0.5\n")
	b.WriteString("    target_ratio: 0.2\n")
	b.WriteString("    protect_last: 20\n")
	b.WriteString("    max_passes: 3\n\n")

	fmt.Fprintf(&b, "terminal:\n  backend: %s\n\n", terminalBackend)

	b.WriteString("storage:\n")
	b.WriteString("  driver: sqlite\n")
	fmt.Fprintf(&b, "  sqlite_path: %s\n", storagePath)

	return b.String()
}

func activeProviderBlock(p providerTemplate, apiKey, model string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "  %s:\n", p.Name)
	fmt.Fprintf(&b, "    provider: %s\n", p.Name)
	if p.BaseURL != "" {
		fmt.Fprintf(&b, "    base_url: %s\n", p.BaseURL)
	}
	if apiKey == "" && p.EnvVar != "" {
		// Resolve env var once at setup time; no env: indirection at load.
		apiKey = os.Getenv(p.EnvVar)
	}
	fmt.Fprintf(&b, "    api_key: %q\n", apiKey)
	fmt.Fprintf(&b, "    model: %s\n", model)
	if p.Name == "wenxin" {
		b.WriteString("    # wenxin also requires secret_key (paste as literal string)\n")
	}
	return b.String()
}

func commentedProviderBlock(p providerTemplate) string {
	var b strings.Builder
	fmt.Fprintf(&b, "  # %s:\n", p.Name)
	fmt.Fprintf(&b, "  #   provider: %s\n", p.Name)
	if p.BaseURL != "" {
		fmt.Fprintf(&b, "  #   base_url: %s\n", p.BaseURL)
	}
	fmt.Fprintf(&b, "  #   api_key: \"\"\n")
	fmt.Fprintf(&b, "  #   model: %s\n", p.Model)
	if p.Name == "wenxin" {
		b.WriteString("  #   # wenxin also requires secret_key (paste as literal string)\n")
	}
	return b.String()
}

func prompt(reader *bufio.Reader, label, def string) string {
	fmt.Printf("%s: ", label)
	line, _ := reader.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}
