/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HermindPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  hermindUrl: "http://127.0.0.1:30000",
  autoAttachContext: true,
  saveFolder: "Hermind Conversations",
  showToolCalls: false
};
var HermindSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Hermind Settings" });
    new import_obsidian.Setting(containerEl).setName("Hermind URL").setDesc("Base URL of the running hermind web server").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:30000").setValue(this.plugin.settings.hermindUrl).onChange(async (value) => {
        this.plugin.settings.hermindUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-attach context").setDesc("Automatically include current note and selection in messages").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoAttachContext).onChange(async (value) => {
        this.plugin.settings.autoAttachContext = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Save folder").setDesc("Default folder for saved conversations").addText(
      (text) => text.setPlaceholder("Hermind Conversations").setValue(this.plugin.settings.saveFolder).onChange(async (value) => {
        this.plugin.settings.saveFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show tool calls").setDesc("Expand tool call details in chat messages").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showToolCalls).onChange(async (value) => {
        this.plugin.settings.showToolCalls = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/chat/ChatView.ts
var import_obsidian4 = require("obsidian");

// src/api.ts
var import_obsidian2 = require("obsidian");
var HermindAPI = class {
  constructor(baseUrl) {
    this.baseUrl = baseUrl;
  }
  async sendMessage(message, ctx) {
    const body = { user_message: message };
    if (ctx) {
      body.obsidian_context = ctx;
    }
    await (0, import_obsidian2.requestUrl)({
      url: `${this.baseUrl}/api/conversation/messages`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body)
    });
  }
  async cancel() {
    await (0, import_obsidian2.requestUrl)({
      url: `${this.baseUrl}/api/conversation/cancel`,
      method: "POST"
    });
  }
};

// src/sse.ts
var HermindSSE = class {
  constructor(baseUrl, onEvent, onError) {
    this.baseUrl = baseUrl;
    this.onEvent = onEvent;
    this.onError = onError;
    this.eventSource = null;
    this.reconnectAttempts = 0;
    this.maxReconnects = 3;
  }
  connect() {
    this.disconnect();
    this.eventSource = new EventSource(`${this.baseUrl}/api/sse`);
    this.eventSource.onmessage = (evt) => {
      try {
        const parsed = JSON.parse(evt.data);
        this.onEvent(parsed);
        if (parsed.type === "done" || parsed.type === "error") {
          this.reconnectAttempts = 0;
        }
      } catch (e) {
      }
    };
    this.eventSource.onerror = () => {
      this.onError("SSE connection lost");
      this.tryReconnect();
    };
  }
  disconnect() {
    if (this.eventSource) {
      this.eventSource.close();
      this.eventSource = null;
    }
  }
  tryReconnect() {
    if (this.reconnectAttempts >= this.maxReconnects) {
      this.onError("SSE reconnection failed after 3 attempts");
      return;
    }
    this.reconnectAttempts++;
    setTimeout(() => this.connect(), 2e3);
  }
};

// src/context.ts
var import_obsidian3 = require("obsidian");
function extractContext(app) {
  const vaultPath = app.vault.adapter.basePath;
  if (!vaultPath) {
    return void 0;
  }
  const ctx = { vault_path: vaultPath };
  const activeView = app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
  if (activeView) {
    const file = activeView.file;
    if (file) {
      ctx.current_note = file.path;
    }
    const editor = activeView.editor;
    const selection = editor.getSelection();
    if (selection && selection.trim().length > 0) {
      ctx.selected_text = selection;
    }
    const cursor = editor.getCursor();
    ctx.cursor_line = cursor.line + 1;
  }
  return ctx;
}

// src/chat/ChatUI.ts
var ChatUI = class {
  constructor(parent, opts) {
    this.currentAssistantEl = null;
    this.opts = opts;
    this.container = parent.createDiv({ cls: "hermind-chat-container" });
    this.container.style.display = "flex";
    this.container.style.flexDirection = "column";
    this.container.style.height = "100%";
    this.errorEl = this.container.createDiv({ cls: "hermind-error" });
    this.errorEl.style.display = "none";
    this.errorEl.style.color = "var(--text-error)";
    this.errorEl.style.padding = "8px";
    this.errorEl.style.fontSize = "12px";
    this.messagesEl = this.container.createDiv({ cls: "hermind-messages" });
    this.messagesEl.style.flex = "1";
    this.messagesEl.style.overflowY = "auto";
    this.messagesEl.style.padding = "8px";
    const inputContainer = this.container.createDiv({ cls: "hermind-input-container" });
    inputContainer.style.padding = "8px";
    inputContainer.style.borderTop = "1px solid var(--background-modifier-border)";
    inputContainer.style.display = "flex";
    inputContainer.style.gap = "8px";
    this.inputEl = inputContainer.createEl("textarea");
    this.inputEl.style.flex = "1";
    this.inputEl.style.resize = "none";
    this.inputEl.style.height = "60px";
    this.inputEl.placeholder = "Ask hermind...";
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.submit();
      }
    });
    const sendBtn = inputContainer.createEl("button", { text: "Send" });
    sendBtn.onclick = () => this.submit();
    const saveBtn = inputContainer.createEl("button", { text: "Save" });
    saveBtn.onclick = () => this.opts.onSave();
  }
  addMessage(msg) {
    const el = this.messagesEl.createDiv({ cls: `hermind-message hermind-message-${msg.role}` });
    el.style.marginBottom = "12px";
    el.style.padding = "8px";
    el.style.borderRadius = "6px";
    el.style.backgroundColor = msg.role === "user" ? "var(--background-modifier-form-field)" : "var(--background-primary-alt)";
    el.createEl("div", { text: msg.content });
    if (msg.toolCalls && this.opts.showToolCalls) {
      for (const tc of msg.toolCalls) {
        this.renderToolCall(el, tc);
      }
    }
  }
  startAssistantMessage() {
    this.currentAssistantEl = this.messagesEl.createDiv({ cls: "hermind-message hermind-message-assistant" });
    this.currentAssistantEl.style.marginBottom = "12px";
    this.currentAssistantEl.style.padding = "8px";
    this.currentAssistantEl.style.borderRadius = "6px";
    this.currentAssistantEl.style.backgroundColor = "var(--background-primary-alt)";
  }
  updateAssistantMessage(text) {
    if (!this.currentAssistantEl)
      return;
    this.currentAssistantEl.empty();
    this.currentAssistantEl.createEl("div", { text });
  }
  finalizeAssistantMessage() {
    this.currentAssistantEl = null;
  }
  addToolCall(id, tc) {
    if (!this.currentAssistantEl || !this.opts.showToolCalls)
      return;
    const el = this.currentAssistantEl.createDiv({ cls: "hermind-tool-call" });
    el.style.fontSize = "11px";
    el.style.color = "var(--text-muted)";
    el.createEl("div", { text: `\u{1F527} ${tc.name}` });
  }
  updateToolCallResult(id, result) {
  }
  renderToolCall(parent, tc) {
    const el = parent.createDiv({ cls: "hermind-tool-call" });
    el.style.fontSize = "11px";
    el.style.color = "var(--text-muted)";
    el.createEl("div", { text: `\u{1F527} ${tc.name}` });
  }
  showError(msg) {
    this.errorEl.style.display = "block";
    this.errorEl.setText(msg);
    setTimeout(() => {
      this.errorEl.style.display = "none";
    }, 5e3);
  }
  submit() {
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    this.inputEl.value = "";
    this.opts.onSend(text);
  }
};

// src/chat/ChatView.ts
var VIEW_TYPE_HERMIND = "hermind-chat-view";
var ChatView = class extends import_obsidian4.ItemView {
  constructor(leaf, settings) {
    super(leaf);
    this.settings = settings;
    this.messages = [];
    this.currentAssistantMessage = "";
    this.currentToolCalls = {};
    this.api = new HermindAPI(settings.hermindUrl);
    this.sse = new HermindSSE(
      settings.hermindUrl,
      (evt) => this.handleSSE(evt),
      (msg) => {
        var _a;
        return (_a = this.ui) == null ? void 0 : _a.showError(msg);
      }
    );
  }
  getViewType() {
    return VIEW_TYPE_HERMIND;
  }
  getDisplayText() {
    return "Hermind";
  }
  async onOpen() {
    this.ui = new ChatUI(this.containerEl, {
      onSend: (text) => this.sendMessage(text),
      onSave: () => this.saveConversation(),
      showToolCalls: this.settings.showToolCalls
    });
    this.sse.connect();
  }
  async onClose() {
    this.sse.disconnect();
  }
  sendSelection(selection) {
    this.sendMessage(selection);
  }
  async sendMessage(text) {
    const userMsg = { id: crypto.randomUUID(), role: "user", content: text };
    this.messages.push(userMsg);
    this.ui.addMessage(userMsg);
    this.currentAssistantMessage = "";
    this.currentToolCalls = {};
    this.ui.startAssistantMessage();
    try {
      const ctx = this.settings.autoAttachContext ? extractContext(this.app) : void 0;
      await this.api.sendMessage(text, ctx);
    } catch (err) {
      this.ui.showError(`Failed to send: ${err}`);
    }
  }
  handleSSE(evt) {
    switch (evt.type) {
      case "message_chunk":
        this.currentAssistantMessage += evt.data.text || "";
        this.ui.updateAssistantMessage(this.currentAssistantMessage);
        break;
      case "tool_call": {
        const id = evt.data.id;
        this.currentToolCalls[id] = {
          name: evt.data.name,
          input: evt.data.input
        };
        this.ui.addToolCall(id, this.currentToolCalls[id]);
        break;
      }
      case "tool_result": {
        const id = evt.data.id;
        if (this.currentToolCalls[id]) {
          this.currentToolCalls[id].result = evt.data.result;
          this.ui.updateToolCallResult(id, this.currentToolCalls[id].result);
        }
        break;
      }
      case "done": {
        const assistantMsg = {
          id: crypto.randomUUID(),
          role: "assistant",
          content: this.currentAssistantMessage,
          toolCalls: Object.entries(this.currentToolCalls).map(([id, tc]) => ({
            id,
            name: tc.name,
            input: tc.input,
            result: tc.result
          }))
        };
        this.messages.push(assistantMsg);
        this.ui.finalizeAssistantMessage();
        break;
      }
      case "error":
        this.ui.showError(evt.data.message);
        break;
    }
  }
  async saveConversation() {
    var _a;
    if (this.messages.length === 0)
      return;
    const folder = this.settings.saveFolder || "Hermind Conversations";
    await this.app.vault.createFolder(folder).catch(() => {
    });
    const date = new Date().toISOString().replace(/[:T]/g, "-").slice(0, 19);
    const firstUserMsg = ((_a = this.messages.find((m) => m.role === "user")) == null ? void 0 : _a.content.slice(0, 30)) || "conversation";
    const safeName = firstUserMsg.replace(/[^a-z0-9\u4e00-\u9fa5]/gi, " ").trim().replace(/\s+/g, "-");
    const fileName = `${folder}/${date}-${safeName}.md`;
    const lines = [
      "---",
      `title: "Hermind Conversation"`,
      `date: ${new Date().toISOString()}`,
      `tags: [hermind, conversation]`,
      `message_count: ${this.messages.length}`,
      "---",
      ""
    ];
    for (const msg of this.messages) {
      lines.push(`## ${msg.role === "user" ? "User" : "Assistant"}`);
      lines.push("");
      lines.push(msg.content);
      lines.push("");
    }
    await this.app.vault.create(fileName, lines.join("\n"));
  }
};

// src/main.ts
var HermindPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_HERMIND, (leaf) => new ChatView(leaf, this.settings));
    this.addRibbonIcon("message-circle", "Open Hermind Chat", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-hermind-chat",
      name: "Open Hermind Chat",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "send-selection-to-hermind",
      name: "Send Selection to Hermind",
      callback: () => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
        if (!view)
          return;
        const selection = view.editor.getSelection();
        if (!selection)
          return;
        this.activateView().then(() => {
          const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_HERMIND)[0];
          if (leaf && leaf.view instanceof ChatView) {
            leaf.view.sendSelection(selection);
          }
        });
      }
    });
    this.addSettingTab(new HermindSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_HERMIND);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_HERMIND)[0];
    if (existing) {
      workspace.revealLeaf(existing);
      return;
    }
    const leaf = (_a = workspace.getRightLeaf(false)) != null ? _a : workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE_HERMIND, active: true });
    workspace.revealLeaf(leaf);
  }
};
