#include "HermindCGOClient.h"
#include <QJsonDocument>
#include <QDebug>

// Include the CGO-generated header. This file is generated by
// go build -buildmode=c-archive in the CMake build step.
extern "C" {
#include "go-desktop-interface.h"
}

HermindCGOClient::HermindCGOClient(QObject *parent)
    : QObject(parent)
{
}

QJsonObject HermindCGOClient::doCall(const QString &method, const QString &path,
                                      const QJsonObject &body)
{
    QByteArray bodyBytes;
    const char *bodyPtr = nullptr;
    int bodyLen = 0;
    if (!body.isEmpty()) {
        bodyBytes = QJsonDocument(body).toJson(QJsonDocument::Compact);
        bodyPtr = bodyBytes.constData();
        bodyLen = bodyBytes.length();
    }

    int respLen = 0;
    void *resp = HermindCall(
        method.toUtf8().constData(),
        path.toUtf8().constData(),
        bodyPtr,
        bodyLen,
        &respLen
    );

    if (resp == nullptr) {
        return QJsonObject{{"ok", false}, {"error", "null response from Go"}};
    }

    QByteArray respData(static_cast<const char*>(resp), respLen);
    HermindFree(resp);

    QJsonDocument doc = QJsonDocument::fromJson(respData);
    if (doc.isNull() || !doc.isObject()) {
        return QJsonObject{{"ok", false}, {"error", "invalid JSON from Go"}};
    }
    return doc.object();
}

void HermindCGOClient::get(const QString &path, Callback callback)
{
    QJsonObject resp = doCall(QStringLiteral("GET"), path);
    bool ok = resp.value(QStringLiteral("ok")).toBool();
    if (ok) {
        callback(resp.value(QStringLiteral("data")).toObject(), QString());
    } else {
        callback(QJsonObject(), resp.value(QStringLiteral("error")).toString());
    }
}

void HermindCGOClient::post(const QString &path, const QJsonObject &body, Callback callback)
{
    QJsonObject resp = doCall(QStringLiteral("POST"), path, body);
    bool ok = resp.value(QStringLiteral("ok")).toBool();
    if (ok) {
        callback(resp.value(QStringLiteral("data")).toObject(), QString());
    } else {
        callback(QJsonObject(), resp.value(QStringLiteral("error")).toString());
    }
}

void HermindCGOClient::put(const QString &path, const QJsonObject &body, Callback callback)
{
    QJsonObject resp = doCall(QStringLiteral("PUT"), path, body);
    bool ok = resp.value(QStringLiteral("ok")).toBool();
    if (ok) {
        callback(resp.value(QStringLiteral("data")).toObject(), QString());
    } else {
        callback(QJsonObject(), resp.value(QStringLiteral("error")).toString());
    }
}

void HermindCGOClient::delete_(const QString &path, Callback callback)
{
    QJsonObject resp = doCall(QStringLiteral("DELETE"), path);
    bool ok = resp.value(QStringLiteral("ok")).toBool();
    if (ok) {
        callback(resp.value(QStringLiteral("data")).toObject(), QString());
    } else {
        callback(QJsonObject(), resp.value(QStringLiteral("error")).toString());
    }
}

void HermindCGOClient::upload(const QString &path, const QByteArray &data,
                               const QString &fileName, const QString &mimeType,
                               Callback callback)
{
    QJsonObject body;
    body[QStringLiteral("fileName")] = fileName;
    body[QStringLiteral("mimeType")] = mimeType;
    body[QStringLiteral("data")] = QString::fromUtf8(data.toBase64());
    post(path, body, callback);
}

QNetworkReply* HermindCGOClient::getStream(const QString &path)
{
    Q_UNUSED(path)
    return nullptr;
}

// ===== QML API wrappers =====

void HermindCGOClient::invokeJSCallback(QJSValue callback, const QJsonObject &resp, const QString &error)
{
    if (callback.isCallable()) {
        callback.call(QJSValueList()
            << QJSValue(QString(QJsonDocument(resp).toJson(QJsonDocument::Compact)))
            << error);
    }
}

void HermindCGOClient::get(const QString &path, QJSValue jsCallback)
{
    get(path, [jsCallback](const QJsonObject &resp, const QString &error) mutable {
        invokeJSCallback(jsCallback, resp, error);
    });
}

void HermindCGOClient::post(const QString &path, QJsonObject body, QJSValue jsCallback)
{
    post(path, body, [jsCallback](const QJsonObject &resp, const QString &error) mutable {
        invokeJSCallback(jsCallback, resp, error);
    });
}

void HermindCGOClient::put(const QString &path, QJsonObject body, QJSValue jsCallback)
{
    put(path, body, [jsCallback](const QJsonObject &resp, const QString &error) mutable {
        invokeJSCallback(jsCallback, resp, error);
    });
}

void HermindCGOClient::delete_(const QString &path, QJSValue jsCallback)
{
    delete_(path, [jsCallback](const QJsonObject &resp, const QString &error) mutable {
        invokeJSCallback(jsCallback, resp, error);
    });
}

void HermindCGOClient::upload(const QString &path, const QByteArray &data,
                               const QString &fileName, const QString &mimeType,
                               QJSValue jsCallback)
{
    upload(path, data, fileName, mimeType, [jsCallback](const QJsonObject &resp, const QString &error) mutable {
        invokeJSCallback(jsCallback, resp, error);
    });
}
