package processors

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ledongthuc/pdf"
	"github.com/odysseythink/hermind/backend/internal/collector/core"
	"github.com/odysseythink/hermind/backend/internal/collector/external"
	"github.com/odysseythink/hermind/backend/internal/collector/pipeline"
	"github.com/odysseythink/hermind/backend/internal/collector/utils"
)

// PDFExtractor extracts text from PDF files using multiple fallback strategies.
type PDFExtractor struct {
	tesseract   *external.TesseractAdapter
	shellRunner *utils.ShellRunner
}

// NewPDFExtractor creates a new PDFExtractor.
func NewPDFExtractor(tesseract *external.TesseractAdapter, shellRunner *utils.ShellRunner) *PDFExtractor {
	return &PDFExtractor{
		tesseract:   tesseract,
		shellRunner: shellRunner,
	}
}

// Supports returns true for the .pdf extension.
func (e *PDFExtractor) Supports(ext string) bool {
	return ext == ".pdf"
}

// Extract attempts to extract text from a PDF using three layers:
//  1. Pure Go (github.com/ledongthuc/pdf)
//  2. pdftotext CLI
//  3. OCR fallback (pdftoppm + tesseract)
func (e *PDFExtractor) Extract(ctx context.Context, input pipeline.ExtractInput) (*pipeline.ExtractOutput, error) {
	// Layer 1: Pure Go extraction.
	content, err := e.extractWithGoPDF(input.FilePath)
	if err == nil && strings.TrimSpace(content) != "" {
		return &pipeline.ExtractOutput{Content: content}, nil
	}

	// Layer 2: pdftotext CLI.
	if e.shellRunner.CheckInstalled("pdftotext") {
		content, err = e.extractWithPdftotext(ctx, input.FilePath)
		if err == nil && strings.TrimSpace(content) != "" {
			return &pipeline.ExtractOutput{Content: content}, nil
		}
	}

	// Layer 3: OCR fallback.
	if e.tesseract != nil && e.tesseract.Available() {
		langList := strings.TrimSpace(input.Options.OCR.LangList)
		if langList == "" {
			return nil, fmt.Errorf("%w: OCR language list is empty; configure TARGET_OCR_LANG", core.ErrEmptyContent)
		}
		if !e.shellRunner.CheckInstalled("pdftoppm") {
			return nil, fmt.Errorf("%w: pdftoppm is not installed; install poppler-utils to OCR scanned PDFs", core.ErrEmptyContent)
		}
		content, err = e.extractWithOCR(ctx, input.FilePath, langList)
		if err == nil && strings.TrimSpace(content) != "" {
			return &pipeline.ExtractOutput{Content: content}, nil
		}
		if err != nil {
			return nil, fmt.Errorf("%w: OCR fallback failed: %v", core.ErrEmptyContent, err)
		}
	}

	return nil, fmt.Errorf("%w: no text content found and OCR tools are not available or configured", core.ErrEmptyContent)
}

func (e *PDFExtractor) extractWithGoPDF(filePath string) (string, error) {
	f, r, err := pdf.Open(filePath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	var buf strings.Builder
	numPages := r.NumPage()
	for i := 1; i <= numPages; i++ {
		p := r.Page(i)
		if p.V.IsNull() {
			continue
		}
		text, err := p.GetPlainText(nil)
		if err != nil {
			continue
		}
		if buf.Len() > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString(text)
	}
	return buf.String(), nil
}

func (e *PDFExtractor) extractWithPdftotext(ctx context.Context, filePath string) (string, error) {
	out, err := e.shellRunner.RunWithTimeout(ctx, utils.DefaultTimeoutPdftotext, "pdftotext", "-layout", filePath, "-")
	if err != nil {
		return "", fmt.Errorf("pdftotext failed: %w", err)
	}
	return out, nil
}

func (e *PDFExtractor) extractWithOCR(ctx context.Context, filePath string, langList string) (string, error) {
	tmpDir, err := os.MkdirTemp("", "collector-pdf-ocr-*")
	if err != nil {
		return "", fmt.Errorf("create temp dir for OCR: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	prefix := filepath.Join(tmpDir, "page")
	_, err = e.shellRunner.RunWithTimeout(ctx, utils.DefaultTimeoutPdftoppm, "pdftoppm", "-png", filePath, prefix)
	if err != nil {
		return "", fmt.Errorf("pdftoppm failed: %w", err)
	}

	matches, err := filepath.Glob(prefix + "-*.png")
	if err != nil {
		return "", fmt.Errorf("glob OCR images: %w", err)
	}
	if len(matches) == 0 {
		return "", fmt.Errorf("no images generated by pdftoppm")
	}

	sort.Strings(matches)

	langs := parseOCRLangs(langList)
	var buf strings.Builder
	for _, imgPath := range matches {
		text, err := e.tesseract.Run(ctx, imgPath, langs)
		if err != nil {
			continue // Skip failed pages
		}
		if buf.Len() > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString(text)
	}

	return buf.String(), nil
}

func parseOCRLangs(langList string) []string {
	var result []string
	for _, part := range strings.Split(langList, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		for _, sub := range strings.Split(part, "+") {
			sub = strings.TrimSpace(sub)
			if sub != "" {
				result = append(result, sub)
			}
		}
	}
	return result
}
